### ISSUE TITLE
Parsing failure: unexpected 'g'; expected }

### ISSUE THREAD

**Issue by doug-episource** [apexsharp/apexsharp#18]
Any idea why the code below generates this error?

Error
`Parsing failure: unexpected 'g'; expected } (Line 4, Column 2); recently consumed: Records;`

Code
```
global class BatchCleanLandingZoneCharts implements Database.Batchable<sObject> {
	global String query;
	global List<sObject> gllstScopeRecords;
	global Datetime yesterday;

	global BatchCleanLandingZoneCharts() {
		yesterday = System.now()-1;
		query = 'SELECT Id, CreatedDate FROM Landing_Zone_Chart__c WHERE CreatedDate < :yesterday';
	}	

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}
 
  	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		gllstScopeRecords = scope;
	}	

	global void finish(Database.BatchableContext BC) {
	}	
}
```
Really looking forward to trying this out further and really appreciate the hard work on this.

**Comment by yallie** [comment]
Hi Doug,

thanks for reporting! Looks like the problem is related to the `yesterday` keyword.
It's listed as a reserved word in the official Apex documentation here:
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_reserved_words.htm

Apparently it's not reserved if you can use it as a variable name.
I've updated the parser and removed `yesterday` from the list of reserved words.
Please update the ApexParser nuget package (should be ready within a few minutes).

Alternatively, you can just rename `yesterday` variable to something else :)

Regards, Alex

**Comment by doug-episource** [comment]
Hahaha, thanks, I should have caught that... Also, thanks for fixing it so quickly. I am really excited to try this out. I am building a POC of pulling some very data and CPU intensive code out of SF, and this will help immensely. I have a long history with C#, too, and I am very curious about the C# -> Apex angle, as well. Again, thanks for the very quick response and for doing this for the community.
